[features]
seeds = false
skip-lint = false
[programs.localnet]
unstake_my_sol = "2s5Phqos3TVKh6CyuFqm8vQukzxueJfMWgtci224h9qc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/GYjR1mO4JjwZ1mC6LLuwCVrFWFLY6BWX"
wallet = "/home/nick/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
